### ISSUE TITLE
Angular Console and support for NRWL nx projects

### ISSUE THREAD

**Issue by matthewharwood** [chgc/ngcli-wallaby#1]
Could we get instructions on how to fix the ng add for nrwl nx projects? Or even better a flag to pass for install in nrwl projects?

e.g. `ng add ngcli-wallaby --nx`

**Comment by chgc** [comment]
Hi, Yes, this feature I have been thinking and try to add it.
It still have few minor issues left. Once I finish it, it should be able to add wallaby.js config in NX project.
In the meantime, you can read some information from [here](https://github.com/TomWhiteOmni/angular-nx-wallaby)

**Comment by chgc** [comment]
package version 0.2.16 now should work fine with nx project
